"""Aggregate the pixel dataset to per-ward statistics for the simulator (plan §12).

Reads data/processed/kochi_samples.parquet + configs/wards_kochi.geojson, computes per-ward
mean LST/NDVI/NDBI/albedo (+ pixel count), simplifies geometry, and writes a self-contained
JS data file the simulator page includes directly (no server / no CORS needed):

    web/ward_data.js   ->  window.WARD_DATA (GeoJSON) and window.CLIMATE (scene-mean forcing)

Wards with no land pixels (water-dominated islands/backwaters) fall back to the city-mean LST
and are flagged has_data=false.
"""

import json

import pandas as pd
from shapely.geometry import shape, mapping

PARQUET = "data/processed/kochi_samples.parquet"
WARDS = "configs/wards_kochi.geojson"
OUT = "web/ward_data.js"
SIMPLIFY_TOL = 0.0003   # ~33 m, to shrink the embedded geometry


def main():
    df = pd.read_parquet(PARQUET)
    df["lst_c"] = df["lst"] - 273.15

    g = df.groupby("ward_id")
    agg = g.agg(lst_c=("lst_c", "mean"), ndvi=("ndvi", "mean"), ndbi=("ndbi", "mean"),
                albedo=("albedo", "mean"), npix=("lst_c", "size")).to_dict("index")

    city = {
        "lst_c": float(df.lst_c.mean()), "ndvi": float(df.ndvi.mean()),
        "ndbi": float(df.ndbi.mean()), "albedo": float(df.albedo.mean()),
    }
    climate = {
        "s_down": float(df.s_down.mean()), "t_air_k": float(df.t_air.mean()),
        "wind": float(df.wind.mean()), "rh": float(df.rh.mean()),
    }

    wards = json.load(open(WARDS, encoding="utf-8"))
    out_feats = []
    for f in wards["features"]:
        wid = f["properties"]["ward_id"]
        geom = shape(f["geometry"]).simplify(SIMPLIFY_TOL, preserve_topology=True)
        a = agg.get(wid)
        has = a is not None
        props = {
            "ward_id": wid,
            "ward_name": f["properties"].get("ward_name") or f"Ward {wid}",
            "ward_no": f["properties"].get("ward_no"),
            "has_data": has,
            "npix": int(a["npix"]) if has else 0,
            "lst_c": round(a["lst_c"] if has else city["lst_c"], 2),
            "ndvi": round(a["ndvi"] if has else city["ndvi"], 3),
            "ndbi": round(a["ndbi"] if has else city["ndbi"], 3),
            "albedo": round(a["albedo"] if has else city["albedo"], 3),
        }
        out_feats.append({"type": "Feature", "geometry": mapping(geom), "properties": props})

    fc = {"type": "FeatureCollection", "features": out_feats}
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by scripts/build_ward_stats.py — do not edit by hand.\n")
        fh.write("window.WARD_DATA = " + json.dumps(fc, separators=(",", ":")) + ";\n")
        fh.write("window.CLIMATE = " + json.dumps(climate) + ";\n")
        fh.write("window.CITY = " + json.dumps({k: round(v, 3) for k, v in city.items()}) + ";\n")

    n_data = sum(p["properties"]["has_data"] for p in out_feats)
    print(f"Wrote {OUT}: {len(out_feats)} wards ({n_data} with data), "
          f"city mean LST {city['lst_c']:.1f} C")
    print(f"Climate means: S_down {climate['s_down']:.0f} W/m2, "
          f"T_air {climate['t_air_k']-273.15:.1f} C, wind {climate['wind']:.2f} m/s, RH {climate['rh']:.0f}%")


if __name__ == "__main__":
    main()
